[package]
name = "pyfind"
version = "0.1.0"
authors = ["andrewPoulton <awdpoulton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
colored = "1.9"
argparse = "0.2.2"
fstream = "0.1.2"